name: Test

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Start containers
      run: docker compose -f "docker-compose.yaml" up -d --build

    - name: Run model validation inside docker container
      timeout-minutes: 5
      run: |
        echo "Starting Cube.js schema validation..."

        # Start validation in the background
        docker compose exec cube_api sh -c "cubejs validate" 2>&1 | while IFS= read -r line; do
          echo "$line"
        
          if echo "$line" | grep -q "✅ Cube Schema is valid"; then
            echo "SUCCESS: Cube Schema validation completed"
            exit 0
            kill $$  # Kill this shell to exit immediately
          fi
        done
        
        # If it gets here, validation failed or hung indefinitely
        echo "FAILED: Schema validation did not complete successfully"
        exit 1


    - name: Run tests
      run: npm run test

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yaml" down

   
