name: Test

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Start containers
      run: docker compose -f "docker-compose.yaml" up -d --build

    - name: Run model validation inside docker container
      timeout-minutes: 5
      run: |
        echo "Starting Cube.js schema validation..."

        success=0
        tmpfile=$(mktemp)
        
        # Run cubejs validate in background and capture output to a temp file
        docker compose exec cube_api sh -c "cubejs validate" > "$tmpfile" 2>&1 &
        cmd_pid=$!
        
        # Stream logs line by line while checking for the success message
        tail -f "$tmpfile" --pid=$cmd_pid | while IFS= read -r line; do
          echo "$line"
          if echo "$line" | grep -q "✅ Cube Schema is valid"; then
            success=1
            kill "$cmd_pid" 2>/dev/null
            break
          fi
        done
        
        # Wait for validate process to exit cleanly
        wait "$cmd_pid" 2>/dev/null
        
        # Clean up and return status
        rm "$tmpfile"
        
        if [ "$success" -eq 1 ]; then
          echo "SUCCESS: Cube Schema validation completed"
          exit 0
        else
          echo "FAILED: Schema validation did not complete successfully"
          exit 1
        fi


    - name: Run tests
      run: npm run test

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yaml" down

   
