name: Test

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python 3.11
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt update
        sudo apt install -y python3.11 python3.11-dev python3.11-venv
        python3.11 --version

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Start containers
      run: docker compose -f "docker-compose.yaml" up -d --build

    - name: run validate with npx
      run: npx cubejs-cli validate

    - name: Run model validation inside docker container
      timeout-minutes: 5
      run: |
        echo "Starting Cube.js schema validation..."
        
        success=0
        
        # Run validate and stream its output
        docker compose exec cube_api sh -c "cubejs validate" 2>&1 | while IFS= read -r line; do
          echo "$line"
          if echo "$line" | grep -q "✅ Cube Schema is valid"; then
            success=1
            break
          fi
        done
        
        # Wait for remaining output to flush and process to exit
        # (Otherwise GitHub Actions may think it was terminated early)
        wait
        
        if [ "$success" -eq 1 ]; then
          echo "SUCCESS: Cube Schema validation completed"
          exit 0
        else
          echo "FAILED: Schema validation did not complete successfully"
          exit 1
        fi

    - name: Run tests
      run: npm run test

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yaml" down

   
