name: Test

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Start containers
      run: docker compose -f "docker-compose.yaml" up -d --build

    - name: run validate with npx
      run: npx cubejs-cli validate

    - name: Run model validation inside docker container
      id: docker-validate
      if: always()
      run: |
        echo "Starting Cube.js schema validation..."
        
        success=0
        
        # Run in background and capture PID
        docker compose exec cube_api sh -c "cubejs validate" 2>&1 | {
          while IFS= read -r line; do
            echo "$line"
            if echo "$line" | grep -q "✅ Cube Schema is valid"; then
              success=1
              break
            fi
          done
        
          # echo result to github output
          echo "validation_result: ${success}" >> "$GITHUB_OUTPUT"
        
          # Kill the remaining process if still running
          pkill -P $$ docker 2>/dev/null
          exit "$success"
        }

    - name: Check if docker validation was successful
      if: always()
      run: echo "Result from previous task is ${{ steps.docker-validate.outputs.validation_result }}"

    - name: Run tests
      run: npm run test

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yaml" down

   
